sudo: required
language: cpp
before_script: mkdir build
script: cd build && cmake .. && make

os:
  - linux

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev
    - cmake

before_install:
  - sudo apt-get update -qq

compiler:
  - g++
